image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - chmod +x ./gradlew
  - echo "$SIGNING_CONFIG" > local.properties
  - echo "$SIGNING_KEY_BASE64" | base64 -d > android/app/circuli_key.jks

stages:
  - release
  - deploy

createGitlabRelease:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running the release job"
    - bundle exec fastlane buildFdroid
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - app/build/outputs/apk/*.apk
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Version $CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
    assets:
      links:
        - name: 'fdroid release apk $CI_COMMIT_TAG'
          url: 'https://gitlab.com/api/v4/projects/13/jobs/artifacts/main/download?job=createGitlabRelease'



uploadPlayStoreBeta:
  stage: deploy
  script:
    - echo "Running the uploadPlayStoreBeta job"
    - echo "$SERVICE_JSON" > google_play_api_key.json
    - bundle exec fastlane deployGoogle
  only:
    - main