default:
  image: softartdev/android-fastlane

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - bundle install
  - chmod +x ./gradlew
  - echo -n ${SIGNING_KEY_BASE64} | base64 -d > circuli_key.jks
  - echo "KEY_PATH=../circuli_key.jks" > signing.properties
  - echo "KEY_PASSWORD=${KEY_PASSWORD}" >> signing.properties
  - echo "ALIAS_NAME=${ALIAS_NAME}" >> signing.properties

stages:
  - build
  - release
  - deploy

buildFdroid:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Building F-Droid apk"
    - bundle exec fastlane buildFdroid
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - app/build/outputs/apk/*.apk

createGitlabRelease:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running the release job"
  needs: ["buildFdroid"]
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Version $CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
    assets:
      links:
        - name: 'fdroid release apk $CI_COMMIT_TAG'
          url: 'https://gitlab.com/api/v4/projects/13/jobs/artifacts/main/download?job=createGitlabRelease'



uploadPlayStoreBeta:
  stage: deploy
  script:
    - echo "Running the uploadPlayStoreBeta job"
    - echo ${GPLAY_API_KEY_JSON} > google_play_api_key.json
    - bundle exec fastlane deployGoogle
  only:
    - main