default:
  image: softartdev/android-fastlane

workflow:
  name: 'Circles release workflow'
  rules:
    - if: $CI_COMMIT_TAG

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
#  - release
#  - deploy

before_script:
  - chmod +x ./gradlew
#  - echo -n ${SIGNING_KEY_BASE64} | base64 -d > circuli_key.jks
#  - echo "KEY_PATH=../circuli_key.jks" > signing.properties
#  - echo "KEY_PASSWORD=${KEY_PASSWORD}" >> signing.properties
#  - echo "ALIAS_NAME=${ALIAS_NAME}" >> signing.properties

buildFdroid:
  stage: build
  script:
    - echo "Building F-Droid apk"
    - ./gradlew clean
    - ./gradlew assembleFdroidRelease
    - apt-get update -qy && apt-get upgrade -qy
    - apt-get install -y git
    - git config user.email "taras@futo.org"
    - git config user.name "ci-bot"
    - git remote set-url origin https://gitlab-ci-token:${GITLAB_ACCESS_TOKEN}@gitlab.futo.org/circles/circles-android.git
    - git add -f app/build/outputs/apk/fdroid/release/circles-$CI_COMMIT_TAG-fdroid-release.apk
    - git mv app/build/outputs/apk/fdroid/release/circles-$CI_COMMIT_TAG-fdroid-release.apk .
    - git commit -m "Add F-Droid release apk $CI_COMMIT_TAG"
    - git push origin HEAD:main -o ci.skip
    - git remote set-url origin https://gitlab-ci-token:${FDROID_REPO_GITLAB_ACCESS_TOKEN}@gitlab.futo.org/circles/circles-fdroid-repo.git
    - git add -f circles-$CI_COMMIT_TAG-fdroid-release.apk
    - git mv circles-$CI_COMMIT_TAG-fdroid-release.apk fdroid/repo
    - git commit -m "Add F-Droid release apk $CI_COMMIT_TAG"
    - git push origin HEAD:main

#createGitlabRelease:
#  stage: release
#  image: registry.gitlab.com/gitlab-org/release-cli:latest
#  script:
#    - echo "Running the release job"
#  release:
#    tag_name: $CI_COMMIT_TAG
#    name: 'Version $CI_COMMIT_TAG'
#    description: 'Release created using the release-cli.'
#    assets:
#      links:
#        - name: 'F-Droid release apk $CI_COMMIT_TAG'
#          url: 'https://gitlab.futo.org/circles/circles-android/-/raw/main/app/build/outputs/apk/fdroid/release/circles-$CI_COMMIT_TAG-fdroid-release.apk?ref_type=heads'
#
#
#
#uploadPlayStoreBeta:
#  stage: deploy
#  script:
#    - echo "Running the uploadPlayStoreBeta job"
#    - bundle install
#    - echo ${GPLAY_API_KEY_JSON} > google_play_api_key.json
#    - bundle exec fastlane deployGoogle