# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy to the Google Play Beta"
  lane :deployGoogle do
    gradle(task: "clean")
    gradle(
        task: "bundle",
        build_type: "release",
        properties: {
                 "android.injected.signing.store.file" => options[:path],
                 "android.injected.signing.store.password" => options[:password],
                 "android.injected.signing.key.alias" => options[:alias],
                 "android.injected.signing.key.password" => options[:password],
               }
            )
    upload_to_play_store(
        track: "beta",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
    )
  end
end
